apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    type: standard
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
