# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.14
#controlPlaneEndpoint: "kubemaster:6443"
apiServer:
  extraArgs:
    cloud-provider: "aws"
controllerManager:
  extraArgs:
    cloud-provider: "aws"
networking:
  podSubnet: 192.168.0.0/16

#---
#apiVersion: kubeadm.k8s.io/v1beta2
#kind: InitConfiguration
#nodeRegistration:
#  kubeletExtraArgs:
#    cloud-provider: "aws"

---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
